# Generated by Django 2.2.7 on 2020-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='city',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Москва'), (1, 'Питер'), (2, 'Нижний')], default=0, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_adress',
            field=models.CharField(max_length=124, verbose_name='IP Адрес'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='open_link',
            field=models.CharField(max_length=124, verbose_name='Ссылка на открытие'),
        ),
    ]
