# Generated by Django 2.2.7 on 2020-10-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20201012_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Camera')),
            ],
            options={
                'verbose_name': 'Снимок',
                'verbose_name_plural': 'Снимки',
            },
        ),
    ]
