# Generated by Django 2.2.7 on 2020-10-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='adress',
            field=models.CharField(default='', max_length=256, verbose_name='Адрес'),
        ),
    ]
