# Generated by Django 2.2.7 on 2020-10-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_camera_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Camera', verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Изображение'),
        ),
    ]
