# Generated by Django 2.2.7 on 2020-10-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_auto_20201012_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.CharField(max_length=256, verbose_name='Информация'),
        ),
    ]
