# Generated by Django 2.2.7 on 2020-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0009_auto_20201012_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='open_link',
            field=models.URLField(max_length=124, verbose_name='Ссылка на открытие'),
        ),
    ]
