# Generated by Django 2.2.7 on 2020-10-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_auto_20201012_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(verbose_name='Количество секунд')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
    ]
