# Generated by Django 2.2.7 on 2020-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0011_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AddField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
