# Generated by Django 2.2.7 on 2020-10-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0012_auto_20201012_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
    ]
