# Generated by Django 2.2.7 on 2020-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0014_auto_20201012_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_adress',
            field=models.CharField(max_length=124, verbose_name='IP Адрес'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='open_link',
            field=models.CharField(max_length=124, verbose_name='Ссылка на открытие'),
        ),
    ]
