# Generated by Django 2.2.7 on 2020-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0015_auto_20201014_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shot',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AddField(
            model_name='camera',
            name='seconds',
            field=models.PositiveSmallIntegerField(default=1, help_text='При установке параметра учитывать             частоту траффика на конкртеном шлагбауме', verbose_name='Частота считывания'),
        ),
        migrations.AddField(
            model_name='shot',
            name='car',
            field=models.ImageField(default='foo', upload_to='', verbose_name='Само авто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Гражданское'), (1, 'Скорая')], default=0, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True, help_text='Считывать ли данные при работе программы', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Полное изображение'),
        ),
    ]
