# Generated by Django 2.2.7 on 2020-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0016_auto_20201014_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='mask',
            field=models.ImageField(default='foo', upload_to='masks/', verbose_name='Маска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='seconds',
            field=models.PositiveSmallIntegerField(default=1, help_text='При установке параметра учитывать             частоту траффика на конкртеном шлагбауме', verbose_name='Частота считывания (секунд)'),
        ),
    ]
