# Generated by Django 2.2.7 on 2020-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0017_auto_20201014_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='proba',
            field=models.FloatField(default=0, verbose_name='Уверенность модели'),
            preserve_default=False,
        ),
    ]
