# Generated by Django 2.2.7 on 2020-10-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0018_shot_proba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=False, help_text='Считываются ли данные при работе программы', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Скорая'), (1, 'Гражданское')], default=0, verbose_name='Класс'),
        ),
    ]
