# Generated by Django 2.2.7 on 2020-10-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0019_auto_20201014_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='proba',
        ),
    ]
