# Generated by Django 2.2.7 on 2020-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0020_remove_shot_proba'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='wrong_label',
            field=models.BooleanField(default=False, help_text='При дообучении модели поставить             флаг и изменить класс на верный', verbose_name='Ошибка в классификации'),
        ),
    ]
