# Generated by Django 2.2.7 on 2020-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0021_shot_wrong_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='min_height',
            field=models.IntegerField(default=150, verbose_name='Минимальная высота автомобиля'),
        ),
        migrations.AddField(
            model_name='camera',
            name='min_width',
            field=models.IntegerField(default=150, verbose_name='Минимальная ширина автомобиля'),
        ),
    ]
